/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsNextRouteImport } from './routes/whats-next'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as DashboardYouRouteImport } from './routes/dashboard.you'
import { Route as DashboardTrainRouteImport } from './routes/dashboard.train'
import { Route as DashboardTodayRouteImport } from './routes/dashboard.today'
import { Route as DashboardScheduleNewRouteImport } from './routes/dashboard.schedule-new'
import { Route as DashboardScheduleRouteImport } from './routes/dashboard.schedule'
import { Route as DashboardRidesRouteImport } from './routes/dashboard.rides'
import { Route as ClubsNewRouteImport } from './routes/clubs.new'

const WhatsNextRoute = WhatsNextRouteImport.update({
  id: '/whats-next',
  path: '/whats-next',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardYouRoute = DashboardYouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrainRoute = DashboardTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTodayRoute = DashboardTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScheduleNewRoute = DashboardScheduleNewRouteImport.update({
  id: '/schedule-new',
  path: '/schedule-new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScheduleRoute = DashboardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRidesRoute = DashboardRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => DashboardRoute,
} as any)
const ClubsNewRoute = ClubsNewRouteImport.update({
  id: '/clubs/new',
  path: '/clubs/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/whats-next': typeof WhatsNextRoute
  '/clubs/new': typeof ClubsNewRoute
  '/dashboard/rides': typeof DashboardRidesRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/schedule-new': typeof DashboardScheduleNewRoute
  '/dashboard/today': typeof DashboardTodayRoute
  '/dashboard/train': typeof DashboardTrainRoute
  '/dashboard/you': typeof DashboardYouRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/whats-next': typeof WhatsNextRoute
  '/clubs/new': typeof ClubsNewRoute
  '/dashboard/rides': typeof DashboardRidesRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/schedule-new': typeof DashboardScheduleNewRoute
  '/dashboard/today': typeof DashboardTodayRoute
  '/dashboard/train': typeof DashboardTrainRoute
  '/dashboard/you': typeof DashboardYouRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/whats-next': typeof WhatsNextRoute
  '/clubs/new': typeof ClubsNewRoute
  '/dashboard/rides': typeof DashboardRidesRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/schedule-new': typeof DashboardScheduleNewRoute
  '/dashboard/today': typeof DashboardTodayRoute
  '/dashboard/train': typeof DashboardTrainRoute
  '/dashboard/you': typeof DashboardYouRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/whats-next'
    | '/clubs/new'
    | '/dashboard/rides'
    | '/dashboard/schedule'
    | '/dashboard/schedule-new'
    | '/dashboard/today'
    | '/dashboard/train'
    | '/dashboard/you'
    | '/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/whats-next'
    | '/clubs/new'
    | '/dashboard/rides'
    | '/dashboard/schedule'
    | '/dashboard/schedule-new'
    | '/dashboard/today'
    | '/dashboard/train'
    | '/dashboard/you'
    | '/join/$code'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/whats-next'
    | '/clubs/new'
    | '/dashboard/rides'
    | '/dashboard/schedule'
    | '/dashboard/schedule-new'
    | '/dashboard/today'
    | '/dashboard/train'
    | '/dashboard/you'
    | '/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  WhatsNextRoute: typeof WhatsNextRoute
  ClubsNewRoute: typeof ClubsNewRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whats-next': {
      id: '/whats-next'
      path: '/whats-next'
      fullPath: '/whats-next'
      preLoaderRoute: typeof WhatsNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/you': {
      id: '/dashboard/you'
      path: '/you'
      fullPath: '/dashboard/you'
      preLoaderRoute: typeof DashboardYouRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/train': {
      id: '/dashboard/train'
      path: '/train'
      fullPath: '/dashboard/train'
      preLoaderRoute: typeof DashboardTrainRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/today': {
      id: '/dashboard/today'
      path: '/today'
      fullPath: '/dashboard/today'
      preLoaderRoute: typeof DashboardTodayRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedule-new': {
      id: '/dashboard/schedule-new'
      path: '/schedule-new'
      fullPath: '/dashboard/schedule-new'
      preLoaderRoute: typeof DashboardScheduleNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedule': {
      id: '/dashboard/schedule'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rides': {
      id: '/dashboard/rides'
      path: '/rides'
      fullPath: '/dashboard/rides'
      preLoaderRoute: typeof DashboardRidesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/clubs/new': {
      id: '/clubs/new'
      path: '/clubs/new'
      fullPath: '/clubs/new'
      preLoaderRoute: typeof ClubsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardRidesRoute: typeof DashboardRidesRoute
  DashboardScheduleRoute: typeof DashboardScheduleRoute
  DashboardScheduleNewRoute: typeof DashboardScheduleNewRoute
  DashboardTodayRoute: typeof DashboardTodayRoute
  DashboardTrainRoute: typeof DashboardTrainRoute
  DashboardYouRoute: typeof DashboardYouRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRidesRoute: DashboardRidesRoute,
  DashboardScheduleRoute: DashboardScheduleRoute,
  DashboardScheduleNewRoute: DashboardScheduleNewRoute,
  DashboardTodayRoute: DashboardTodayRoute,
  DashboardTrainRoute: DashboardTrainRoute,
  DashboardYouRoute: DashboardYouRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  WhatsNextRoute: WhatsNextRoute,
  ClubsNewRoute: ClubsNewRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
